### PR TITLE
ContactForm and users update + Address table created

### PR DESCRIPTION
**Pull request by nehakerung**
## Describe your changes
I made a few comments - nothing that will affect site.

Added **Address table** with the general slots + FK to user id.

Updated **users table** to include contact details - just phone number with an additional option if they want to be contacted by email or text. (The website will need to add a contact details section for this; just some tickboxes for fun).
Added an Admin(which returns True/False if admin or not) as well which we can use later to implement admin functions.

Changed **ContactsForm** which will need attention.
**ContactForm - if you have already migrated this, please delete table from your SQL database first**
:( sorry Did not want to do a new update table for this.

Everything can migrate smoothly after though.

## Checklist before requesting a review

- [x] I have tested my code, everything is working fine and I did not break anything.
**ContactForm - if you have already migrated this, please delete it from your database and php artisan migrate again**
:( sorry Did not want to do a new update table for this.
Everything can migrate smoothly after though.

- [x] I have uploaded a screen recording of feature/bugfix if required.

### CODE REVIEW

**Review by KishanJ22 — APPROVED** [review]
All code is good to be merged to main

**Comment by NextPr0gram** [comment]
image
is this for the contact form?
can you add a field called message content please, cos the subject is the title and message content contains the message content.

**Review by NextPr0gram — CHANGES_REQUESTED** [review]
add message content field please, everything else is fine

**Review by NextPr0gram — APPROVED** [review]
all good :D

**Pull request merged**
